apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "procscan.fullname" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "procscan.labels" . | nindent 4 }}
data:
  config.yaml: |
    scanner:
      proc_path: {{ .Values.config.scanner.proc_path | quote }}
      scan_interval: {{ .Values.config.scanner.scan_interval | quote }}
      rules_refresh_interval: {{ .Values.config.scanner.rules_refresh_interval | quote }}
      health_port: {{ .Values.config.scanner.health_port }}
      log_level: {{ .Values.config.scanner.log_level | quote }}

    notifications:
      admin:
        base_url: {{ .Values.config.notifications.admin.base_url | quote }}
        timeout: {{ .Values.config.notifications.admin.timeout | quote }}
        basic_auth:
          username: {{ .Values.config.notifications.admin.basic_auth.username | quote }}
          password: {{ .Values.config.notifications.admin.basic_auth.password | quote }}

    metrics:
      enabled: {{ .Values.config.metrics.enabled }}
      port: {{ .Values.config.metrics.port }}
      path: {{ .Values.config.metrics.path | quote }}
